import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.css"
import SessionWrapper from "../../auth/SessionWrapper"
import Authentication from "../../auth/Authentication"
import { Nav, NavLink } from "@/components/Navbar"
import { Toaster } from "sonner"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={cn(
          "min-h-screen h-screen w-full flex-col bg-background font-sans antialiased",
          fontSans.variable,
          { "debug-screens": process.env.NODE_ENV === "development" }
        )}
      >
        <SessionWrapper>
          <Nav>
            <NavLink href="/">Home</NavLink>
            <NavLink href="/admin">Admin</NavLink>
            <Authentication />
          </Nav>
          {children}
          <Toaster />
        </SessionWrapper>
      </body>
    </html>
  )
}
